# Powerlevel10k config — Flat Pill Design · auto-colored by wallust

() {
  emulate -L zsh

  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # ─── Load wallust hex colors ────────────────────────────────────────────────
  # Generated by wallust into ~/.config/wallust/p10k-colors.zsh on each
  # wallpaper change. Fallbacks are the Retro Programmer palette.
  [[ -f ~/.config/wallust/p10k-colors.zsh ]] && source ~/.config/wallust/p10k-colors.zsh

  local bg="${W_BG:-#0d0019}"
  local c0="${W_C0:-#0d0019}"
  local c1="${W_C1:-#1a0a3e}"
  local c2="${W_C2:-#3d0a5e}"
  local c3="${W_C3:-#5a0f8a}"
  local c4="${W_C4:-#003c1e}"
  local c5="${W_C5:-#500a0a}"
  local c6="${W_C6:-#2a5040}"
  local c7="${W_C7:-#8a6aaa}"
  local c8="${W_C8:-#2a0a50}"
  local c9="${W_C9:-#2a0a50}"
  local c10="${W_C10:-#00c8a0}"
  local c11="${W_C11:-#00e5ff}"
  local c12="${W_C12:-#ff2d78}"
  local c13="${W_C13:-#ff80c0}"
  local c14="${W_C14:-#c8a0ff}"
  local c15="${W_C15:-#f0e0ff}"

  # ─── Prompt elements ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    newline
    prompt_char
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    time
  )

  # ─── Core ───────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # ─── Pill separators ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\ue0b6'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\ue0b4'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\ue0b6'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\ue0b4'

  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\ue0b0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\ue0b2'
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

  typeset -g POWERLEVEL9K_LEFT_LEFT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_LEFT_RIGHT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_RIGHT_LEFT_WHITESPACE=' '
  typeset -g POWERLEVEL9K_RIGHT_RIGHT_WHITESPACE=' '

  # ─── OS icon ────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND="$c5"
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND="$c15"

  # ─── Directory ──────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_DIR_BACKGROUND="$c4"
  typeset -g POWERLEVEL9K_DIR_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND="$c6"
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND="$c13"
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER='…'
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40

  # ─── Git / VCS ──────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND="$c4"
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$c15"

  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="$c5"
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$c15"

  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="$c3"
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$c15"

  typeset -g POWERLEVEL9K_VCS_STAGED_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND="$c15"

  # ─── Prompt char (second line) ──────────────────────────────────────────────
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND="$c13"
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND="$c12"
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  # ─── Status ─────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_BACKGROUND="$c5"
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false

  # ─── Command execution time ──────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="$c3"
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # ─── Background jobs ────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="$c3"
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="$c15"

  # ─── Time ───────────────────────────────────────────────────────────────────
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
  typeset -g POWERLEVEL9K_TIME_BACKGROUND="$c5"
  typeset -g POWERLEVEL9K_TIME_FOREGROUND="$c15"
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # ─── Instant / transient prompt ─────────────────────────────────────────────
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

  (( ! $+functions[p10k] )) || p10k reload
}
