-- Wallust colorscheme — auto-themed by wallust on wallpaper change
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "wallust"
vim.o.termguicolors = true

-- Always reload fresh from disk
package.loaded["colors.wallust-colors"] = nil
local ok, c = pcall(require, "colors.wallust-colors")
if not ok then return end

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ── Editor ────────────────────────────────────────────────────────────
hi("Normal",          { bg = c.bg,  fg = c.fg })
hi("NormalNC",        { bg = c.bg,  fg = c.fg })
hi("NormalFloat",     { bg = c.c0,  fg = c.fg })
hi("FloatBorder",     { bg = c.c0,  fg = c.c4 })
hi("ColorColumn",     { bg = c.c0 })
hi("Conceal",         { fg = c.c8 })
hi("Cursor",          { bg = c.fg,  fg = c.bg })
hi("CursorLine",      { bg = c.c0 })
hi("CursorLineNr",    { fg = c.c14, bold = true })
hi("CursorColumn",    { bg = c.c0 })
hi("Directory",       { fg = c.c12 })
hi("EndOfBuffer",     { fg = c.c0 })
hi("ErrorMsg",        { fg = c.c13, bold = true })
hi("FoldColumn",      { bg = c.bg,  fg = c.c8 })
hi("Folded",          { bg = c.c0,  fg = c.c8, italic = true })
hi("LineNr",          { fg = c.c8 })
hi("MatchParen",      { bg = c.c11, fg = c.bg, bold = true })
hi("ModeMsg",         { fg = c.c14, bold = true })
hi("MoreMsg",         { fg = c.c12 })
hi("NonText",         { fg = c.c0 })
hi("Pmenu",           { bg = c.c0,  fg = c.fg })
hi("PmenuSel",        { bg = c.c4,  fg = c.c15, bold = true })
hi("PmenuSbar",       { bg = c.c0 })
hi("PmenuThumb",      { bg = c.c4 })
hi("Question",        { fg = c.c14 })
hi("QuickFixLine",    { bg = c.c4,  fg = c.c15 })
hi("Search",          { bg = c.c13, fg = c.bg })
hi("IncSearch",       { bg = c.c13, fg = c.bg, bold = true })
hi("CurSearch",       { bg = c.c13, fg = c.bg, bold = true })
hi("SignColumn",      { bg = c.bg,  fg = c.c8 })
hi("SpecialKey",      { fg = c.c8 })
hi("SpellBad",        { sp = c.c13, undercurl = true })
hi("SpellCap",        { sp = c.c5,  undercurl = true })
hi("SpellLocal",      { sp = c.c12, undercurl = true })
hi("SpellRare",       { sp = c.c11, undercurl = true })
hi("StatusLine",      { bg = c.c4,  fg = c.c15, bold = true })
hi("StatusLineNC",    { bg = c.c0,  fg = c.c8 })
hi("Substitute",      { bg = c.c13, fg = c.bg })
hi("TabLine",         { bg = c.c0,  fg = c.c8 })
hi("TabLineFill",     { bg = c.bg })
hi("TabLineSel",      { bg = c.c4,  fg = c.c15, bold = true })
hi("Title",           { fg = c.c14, bold = true })
hi("VertSplit",       { fg = c.c0 })
hi("WinSeparator",    { fg = c.c0 })
hi("Visual",          { bg = c.c4,  fg = c.c15 })
hi("VisualNOS",       { bg = c.c4 })
hi("WarningMsg",      { fg = c.c5,  bold = true })
hi("Whitespace",      { fg = c.c0 })
hi("WildMenu",        { bg = c.c4,  fg = c.c15 })

-- ── Syntax ────────────────────────────────────────────────────────────
hi("Comment",         { fg = c.c8,  italic = true })
hi("Constant",        { fg = c.c6 })
hi("String",          { fg = c.c14 })
hi("Character",       { fg = c.c14 })
hi("Number",          { fg = c.c11 })
hi("Boolean",         { fg = c.c13 })
hi("Float",           { fg = c.c11 })
hi("Identifier",      { fg = c.fg })
hi("Function",        { fg = c.c12 })
hi("Statement",       { fg = c.c13 })
hi("Conditional",     { fg = c.c13 })
hi("Repeat",          { fg = c.c13 })
hi("Label",           { fg = c.c13 })
hi("Operator",        { fg = c.c13 })
hi("Keyword",         { fg = c.c13, bold = true })
hi("Exception",       { fg = c.c13 })
hi("PreProc",         { fg = c.c13 })
hi("Include",         { fg = c.c13 })
hi("Define",          { fg = c.c13 })
hi("Macro",           { fg = c.c13 })
hi("PreCondit",       { fg = c.c13 })
hi("Type",            { fg = c.c11 })
hi("StorageClass",    { fg = c.c13 })
hi("Structure",       { fg = c.c11 })
hi("Typedef",         { fg = c.c11 })
hi("Special",         { fg = c.c6 })
hi("SpecialChar",     { fg = c.c11 })
hi("Tag",             { fg = c.c13 })
hi("Delimiter",       { fg = c.c7 })
hi("SpecialComment",  { fg = c.c8,  italic = true })
hi("Debug",           { fg = c.c13 })
hi("Underlined",      { underline = true })
hi("Error",           { fg = c.c13, bold = true })
hi("Todo",            { bg = c.c11, fg = c.bg, bold = true })

-- ── Diagnostics ───────────────────────────────────────────────────────
hi("DiagnosticError",            { fg = c.c13 })
hi("DiagnosticWarn",             { fg = c.c5 })
hi("DiagnosticInfo",             { fg = c.c12 })
hi("DiagnosticHint",             { fg = c.c14 })
hi("DiagnosticVirtualTextError", { fg = c.c13, bg = c.c0, italic = true })
hi("DiagnosticVirtualTextWarn",  { fg = c.c5,  bg = c.c0, italic = true })
hi("DiagnosticVirtualTextInfo",  { fg = c.c12, bg = c.c0, italic = true })
hi("DiagnosticVirtualTextHint",  { fg = c.c14, bg = c.c0, italic = true })
hi("DiagnosticUnderlineError",   { sp = c.c13, undercurl = true })
hi("DiagnosticUnderlineWarn",    { sp = c.c5,  undercurl = true })
hi("DiagnosticUnderlineInfo",    { sp = c.c12, undercurl = true })
hi("DiagnosticUnderlineHint",    { sp = c.c14, undercurl = true })

-- ── Treesitter ────────────────────────────────────────────────────────
hi("@comment",              { fg = c.c8,  italic = true })
hi("@keyword",              { fg = c.c13, bold = true })
hi("@keyword.function",     { fg = c.c13 })
hi("@keyword.return",       { fg = c.c13 })
hi("@keyword.operator",     { fg = c.c13 })
hi("@conditional",          { fg = c.c13 })
hi("@repeat",               { fg = c.c13 })
hi("@include",              { fg = c.c13 })
hi("@exception",            { fg = c.c13 })
hi("@function",             { fg = c.c12 })
hi("@function.builtin",     { fg = c.c12 })
hi("@function.call",        { fg = c.c12 })
hi("@method",               { fg = c.c12 })
hi("@method.call",          { fg = c.c12 })
hi("@constructor",          { fg = c.c12 })
hi("@variable",             { fg = c.fg })
hi("@variable.builtin",     { fg = c.c13 })
hi("@parameter",            { fg = c.fg })
hi("@field",                { fg = c.c6 })
hi("@property",             { fg = c.c6 })
hi("@string",               { fg = c.c14 })
hi("@string.escape",        { fg = c.c11 })
hi("@string.special",       { fg = c.c11 })
hi("@number",               { fg = c.c11 })
hi("@float",                { fg = c.c11 })
hi("@boolean",              { fg = c.c13 })
hi("@constant",             { fg = c.c6 })
hi("@constant.builtin",     { fg = c.c13 })
hi("@constant.macro",       { fg = c.c13 })
hi("@type",                 { fg = c.c11 })
hi("@type.builtin",         { fg = c.c11 })
hi("@namespace",            { fg = c.c6 })
hi("@operator",             { fg = c.c13 })
hi("@punctuation",          { fg = c.c7 })
hi("@punctuation.bracket",  { fg = c.c7 })
hi("@punctuation.delimiter",{ fg = c.c7 })
hi("@tag",                  { fg = c.c13 })
hi("@tag.attribute",        { fg = c.c6 })
hi("@tag.delimiter",        { fg = c.c7 })
hi("@attribute",            { fg = c.c11 })
hi("@annotation",           { fg = c.c11 })
hi("@label",                { fg = c.c13 })
hi("@storageclass",         { fg = c.c13 })
hi("@structure",            { fg = c.c11 })
hi("@text",                 { fg = c.fg })
hi("@text.title",           { fg = c.c14, bold = true })
hi("@text.emphasis",        { italic = true })
hi("@text.strong",          { bold = true })
hi("@text.uri",             { fg = c.c12, underline = true })
hi("@text.reference",       { fg = c.c6 })
hi("@text.literal",         { fg = c.c14 })
hi("@text.todo",            { bg = c.c11, fg = c.bg, bold = true })
hi("@text.warning",         { fg = c.c5,  bold = true })
hi("@text.danger",          { fg = c.c13, bold = true })

-- ── LSP semantic tokens ───────────────────────────────────────────────
hi("@lsp.type.function",    { fg = c.c12 })
hi("@lsp.type.method",      { fg = c.c12 })
hi("@lsp.type.keyword",     { fg = c.c13, bold = true })
hi("@lsp.type.variable",    { fg = c.fg })
hi("@lsp.type.parameter",   { fg = c.fg })
hi("@lsp.type.property",    { fg = c.c6 })
hi("@lsp.type.type",        { fg = c.c11 })
hi("@lsp.type.class",       { fg = c.c11 })
hi("@lsp.type.interface",   { fg = c.c11 })
hi("@lsp.type.enum",        { fg = c.c11 })
hi("@lsp.type.enumMember",  { fg = c.c6 })
hi("@lsp.type.struct",      { fg = c.c11 })
hi("@lsp.type.namespace",   { fg = c.c6 })
hi("@lsp.type.string",      { fg = c.c14 })
hi("@lsp.type.number",      { fg = c.c11 })
hi("@lsp.type.operator",    { fg = c.c13 })
hi("@lsp.type.comment",     { fg = c.c8,  italic = true })
hi("@lsp.type.decorator",   { fg = c.c11 })
hi("@lsp.type.macro",       { fg = c.c13 })

-- ── GitSigns ──────────────────────────────────────────────────────────
hi("GitSignsAdd",    { fg = c.c6 })
hi("GitSignsChange", { fg = c.c12 })
hi("GitSignsDelete", { fg = c.c13 })

-- ── Telescope ─────────────────────────────────────────────────────────
hi("TelescopeNormal",         { bg = c.c0,  fg = c.fg })
hi("TelescopeBorder",         { bg = c.c0,  fg = c.c4 })
hi("TelescopePromptBorder",   { bg = c.c0,  fg = c.c12 })
hi("TelescopeResultsBorder",  { bg = c.c0,  fg = c.c4 })
hi("TelescopePreviewBorder",  { bg = c.c0,  fg = c.c4 })
hi("TelescopeSelection",      { bg = c.c4,  fg = c.c15 })
hi("TelescopeSelectionCaret", { fg = c.c13 })
hi("TelescopeMatching",       { fg = c.c13, bold = true })
hi("TelescopePromptPrefix",   { fg = c.c12 })

-- ── nvim-cmp ──────────────────────────────────────────────────────────
hi("CmpItemAbbr",           { fg = c.fg })
hi("CmpItemAbbrMatch",      { fg = c.c13, bold = true })
hi("CmpItemAbbrMatchFuzzy", { fg = c.c13 })
hi("CmpItemMenu",           { fg = c.c8 })
hi("CmpItemKind",           { fg = c.c12 })

-- ── which-key ─────────────────────────────────────────────────────────
hi("WhichKey",          { fg = c.c13 })
hi("WhichKeyGroup",     { fg = c.c12 })
hi("WhichKeyDesc",      { fg = c.fg })
hi("WhichKeySeparator", { fg = c.c8 })
hi("WhichKeyFloat",     { bg = c.c0 })

-- ── indent-blankline ──────────────────────────────────────────────────
hi("IndentBlanklineChar",        { fg = c.c0 })
hi("IndentBlanklineContextChar", { fg = c.c4 })
hi("IblIndent",                  { fg = c.c0 })
hi("IblScope",                   { fg = c.c4 })

-- ── Notify ────────────────────────────────────────────────────────────
hi("NotifyERRORBorder", { fg = c.c13 })
hi("NotifyWARNBorder",  { fg = c.c5 })
hi("NotifyINFOBorder",  { fg = c.c12 })
hi("NotifyHINTBorder",  { fg = c.c14 })
hi("NotifyERRORIcon",   { fg = c.c13 })
hi("NotifyWARNIcon",    { fg = c.c5 })
hi("NotifyINFOIcon",    { fg = c.c12 })
hi("NotifyHINTIcon",    { fg = c.c14 })
hi("NotifyERRORTitle",  { fg = c.c13, bold = true })
hi("NotifyWARNTitle",   { fg = c.c5,  bold = true })
hi("NotifyINFOTitle",   { fg = c.c12, bold = true })
hi("NotifyHINTTitle",   { fg = c.c14, bold = true })

-- ── neo-tree / oil ────────────────────────────────────────────────────
hi("NeoTreeNormal",       { bg = c.c0, fg = c.fg })
hi("NeoTreeNormalNC",     { bg = c.c0, fg = c.fg })
hi("NeoTreeDirectoryIcon",{ fg = c.c12 })
hi("NeoTreeDirectoryName",{ fg = c.c12 })
hi("NeoTreeFileName",     { fg = c.fg })
hi("NeoTreeGitAdded",     { fg = c.c6 })
hi("NeoTreeGitModified",  { fg = c.c12 })
hi("NeoTreeGitDeleted",   { fg = c.c13 })
hi("NeoTreeIndentMarker", { fg = c.c0 })
hi("NeoTreeRootName",     { fg = c.c14, bold = true })
